### ISSUE TITLE
"@Deprecated" code should not be used

### ISSUE THREAD

**Issue by piccolo16** [munterkalmsteiner/inception#3]
**Describe the refactoring action**
There is a need for deprecation when the API evolves. Newer and upgraded methods are written, and the older attributed need to be changed. The developers can no longer use the older API methods in the updated version. Once deprecated, classes, and interfaces, and their members should be avoided, rather than used, inherited or extended. Deprecation is a warning that the class or interface has been superseded, and will eventually be removed. 

D:inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBHandle.java
D:inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBHandle.java
D:inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Predictions.java
D:inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/ExtendedId.java
D:inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/util/OverlapIterator.java
D:inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/util/OverlapIterator.java
D:inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/util/OverlapIterator.java
D:inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBHandle.java
D:inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Predictions.java
D:inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/ExtendedId.java
D:inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/util/OverlapIterator.java
D:inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/util/OverlapIterator.java
D:inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/util/OverlapIterator.java
D:inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/util/OverlapIterator.java
D:inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/util/OverlapIterator.java
D:inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Predictions.java
D:inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Predictions.java
D:inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Predictions.java
D:inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
D:inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
D:inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/SuggestionGroup.java
D:inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/SuggestionGroup.java
D:inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBHandle.java
D:inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Offset.java
D:inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Offset.java
D:inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Offset.java
D:inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Offset.java
D:inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Offset.java
D:inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Offset.java
D:inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/exporter/KnowledgeBaseExporter.java
D:inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
D:inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
D:inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/VisibilityCalculationTests.java
D:inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBHandle.java
D:inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBHandle.java
D:inception-log/src/test/java/de/tudarmstadt/ukp/inception/log/EventRepositoryImplIntegrationTest.java
D:inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/LearningRecordServiceImpl.java
D:inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/LearningRecordServiceImpl.java
D:inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/exporter/KnowledgeBaseExporter.java
D:inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/LearningRecordServiceImpl.java

**Expected benefit**
The deprecation period allows you to make a smooth transition away from the aging, soon-to-be-retired technology. The efficiency of the code increases when the deprecated code is removed and it is more secure.

There are a total of 40 instances for this issue which of 10 hours effort. Refactoring depends on the context of the code which needs to be changed.

**Comment by piccolo16** [comment]
@munterkalmsteiner

**Comment by munterkalmsteiner** [comment]
Please be more specific in the issue description. Which files contain deprecated classes/methods? What actual refactoring to you suggest? 
So not simply copy a tool's explanation.

**Comment by piccolo16** [comment]
@munterkalmsteiner Updated the issue and linked the file of locations that contain deprecated methods.
