### ISSUE TITLE
[Mi11]: Override the "equals" method in this class

### ISSUE THREAD

**Issue by AbhinavRamKola** [munterkalmsteiner/inception#35]
**Describe the refactoring action**
This is a minor code smell. By using equals() method it compares the objects and the memory location and checks that the objects are pointing to same memory allocation or not. hashCode() method must be overridden in every class that overrides equals() method. hashCode()  invoked  is used to generate an integer code to that objects. 
 These code smells are found using sonarqube and sonarcloud.
![mi11](https://user-images.githubusercontent.com/39357855/66263049-f4fc8a00-e7ec-11e9-8a1d-c7679ada4aba.PNG)

**Expected benefit**
There is no malfunction when new object or a called object is returned  into another object class as it uses hash methods to perform hashing based collections. Overriding Equals method is required when mapping the values relative to hash based collections. The benefit out of this refactoring is that it ensures the data is going to be stored into the same memory allocation.

**Comment by munterkalmsteiner** [comment]
Just for completeness: your argument for why `hashcode()` must be overridden if `equals()` is overridden is a bit off. See [here](https://www.baeldung.com/java-equals-hashcode-contracts), Section 3, why. It is not about memory, but the assumptions (or contracts) we make when using `equals()` and `hashcode()`.
